// AUTO-GENERATED by tools/character/sync-characters.mjs. Do not edit manually.
import { profile as adamProfile } from "../../adam/profile";
import { createRuntime as createAdamRuntime } from "../../adam/runtime";
import { profile as baronProfile } from "../../baron/profile";
import { createRuntime as createBaronRuntime } from "../../baron/runtime";
import { profile as catronProfile } from "../../catron/profile";
import { createRuntime as createCatronRuntime } from "../../catron/runtime";
import { profile as dakotaProfile } from "../../dakota/profile";
import { createRuntime as createDakotaRuntime } from "../../dakota/runtime";
import { profile as flareProfile } from "../../flare/profile";
import { createRuntime as createFlareRuntime } from "../../flare/runtime";
import { profile as harperProfile } from "../../harper/profile";
import { createRuntime as createHarperRuntime } from "../../harper/runtime";
import { profile as slimluProfile } from "../../slimlu/profile";
import { createRuntime as createSlimluRuntime } from "../../slimlu/runtime";
import type { CharacterEntry, CharacterProfile, CharacterStats } from "../types";

const entries: CharacterEntry[] = [
  { profile: adamProfile, createRuntime: createAdamRuntime },
  { profile: baronProfile, createRuntime: createBaronRuntime },
  { profile: catronProfile, createRuntime: createCatronRuntime },
  { profile: dakotaProfile, createRuntime: createDakotaRuntime },
  { profile: flareProfile, createRuntime: createFlareRuntime },
  { profile: harperProfile, createRuntime: createHarperRuntime },
  { profile: slimluProfile, createRuntime: createSlimluRuntime },
];
const defaultStats: CharacterStats = {
  health: 100,
  stamina: 100,
  mana: 100,
  energy: 100,
};
const profiles: CharacterProfile[] = entries.map((entry) => entry.profile);
const defaultEntry =
  entries.find((entry) => entry.profile.starter) ?? entries[0];

if (!defaultEntry) {
  throw new Error("No character entries registered.");
}

export const resolveCharacterStats = (
  profile?: CharacterProfile
): CharacterStats => ({
  ...defaultStats,
  ...(profile?.stats ?? {}),
});

export const getCharacterEntry = (path?: string) => {
  if (!path) return defaultEntry;
  return entries.find((entry) => path.includes(entry.profile.pathToken)) || defaultEntry;
};

export const characterEntries = entries;
export const characterProfiles = profiles;
export const defaultCharacterEntry = defaultEntry;
export const defaultCharacterPath = `/assets/characters${defaultEntry.profile.pathToken}${defaultEntry.profile.id}.glb`;
